AnnaViktoria/rent_a_dragon

- app/controllers/dragons_controller.rb
- config/routes.rb
- test/controllers/dragons_controller_test.rb
Created a controller - please take a look!
> created dragon controller

- app/controllers/reservations_controller.rb
- test/controllers/reservations_controller_test.rb
created reservations controller
> creating reservationscontroller

- Gemfile
- Gemfile.lock
- app/controllers/dragons_controller.rb
- app/views/dragons/index.html.erb
- app/views/dragons/new.html.erb
- app/views/dragons/show.html.erb
- config/routes.rb
created all the actions for the dragons controller
basic view for index and show
created basic form to create dragon from the show page
> created dragon actions and views

- app/controllers/dragons_controller.rb
> changeddragoncontroller

- app/controllers/dragons_controller.rb
- app/views/dragons/edit.html.erb
- app/views/dragons/index.html.erb
added the edit and update action in the dragon controller
> added edit and update action to dragon controller

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_index.scss
- app/views/dragons/index.html.erb
- app/views/shared/_banner.html.erb
> created a placeholder banner

- Gemfile
- Gemfile.lock
- app/controllers/reservations_controller.rb
- app/views/accounts/index.html.erb
- app/views/dragons/index.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
addapte User to the master project
change the navbar
> merge user master

- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
> customize navbar

- app/assets/stylesheets/components/_background.scss
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_create-form.scss
- app/assets/stylesheets/components/_index.scss
- app/views/dragons/new.html.erb
- app/views/layouts/application.html.erb
added a class to design the forms later
changed background colour to gradient
> changed background color and some front end

- app/assets/stylesheets/components/_background.scss
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/views/dragons/index.html.erb
- app/views/shared/_banner.html.erb
- db/schema.rb
created some cards and made pictures work!
> created basic cards with pictures

- app/javascript/packs/application.js
- app/javascript/plugins/flatpickr.js
now you can see both map and flatpikr
> fixed the js issue

- app/views/dragons/show.html.erb
- db/seeds.rb
changed the locations to better suited ones
> changed the locations

- app/assets/stylesheets/components/_dragon.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_show-title.scss
- app/views/dragons/show.html.erb
> sorted showpage

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_table.scss
- app/controllers/dragons_controller.rb
- app/models/dragon.rb
- app/views/accounts/index.html.erb
- app/views/dragons/index.html.erb
- app/views/layouts/application.html.erb
- db/schema.rb
- db/seeds.rb
> styling account

- app/assets/stylesheets/components/_button.scss
- app/views/accounts/index.html.erb
- app/views/shared/_reservationform.html.erb
- app/views/shared/_review-form.html.erb
created a back to dragons button
> buttons with hover

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_loginform.scss
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
> styling user interface

- app/assets/stylesheets/components/_account-dragon-card.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/pages/_account.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/accounts/index.html.erb
> account style

- app/assets/stylesheets/components/_calendar-form.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/pages/_account.scss
- app/controllers/reservations_controller.rb
- app/javascript/plugins/flatpickr.js
- app/views/accounts/index.html.erb
- app/views/dragons/edit.html.erb
- app/views/shared/_flatpickrform.html.erb
> adpate some pages

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_showpage-background.scss
- app/assets/stylesheets/components/_showpage-picture-boarder.scss
- app/views/dragons/index.html.erb
- app/views/dragons/show.html.erb
> changed showbaggrund and font

- app/assets/stylesheets/components/_button.scss
- app/views/accounts/index.html.erb
- app/views/shared/_flatpickrform.html.erb
- app/views/shared/_review-form.html.erb
> buttons again

- app/assets/stylesheets/components/_card.scss
- app/views/dragons/index.html.erb
- app/views/shared/_banner.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- db/seeds.rb
Changed some locations and the cards, as well as solved the log out issue that was being caused by rails
> changed card and a few other things

- app/assets/stylesheets/components/_account-dragon-card.scss
- app/assets/stylesheets/pages/_account.scss
- app/views/accounts/index.html.erb
- app/views/dragons/edit.html.erb
- app/views/dragons/show.html.erb
- db/migrate/20190815134231_add_price_to_dragon.rb
- db/schema.rb
- db/seeds.rb
> add price column

- app/assets/stylesheets/pages/_account.scss
- app/controllers/dragons_controller.rb
- app/views/accounts/index.html.erb
- app/views/dragons/new.html.erb
- app/views/dragons/show.html.erb
price correction and account style
> price correction and account style

- app/assets/stylesheets/components/_account-dragon-card.scss
- app/assets/stylesheets/components/_background.scss
- app/views/dragons/index.html.erb
> changed account cards

- app/assets/stylesheets/components/_account-dragon-card.scss
- app/views/accounts/index.html.erb
changing the card on the account page
> changing the card

- app/assets/stylesheets/components/_account-dragon-card.scss
- app/views/accounts/index.html.erb
- app/views/dragons/show.html.erb
> adapte price cow

- app/views/accounts/index.html.erb
- app/views/dragons/edit.html.erb
- config/routes.rb
- db/schema.rb
> Fixed delete dragon

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_card.scss
- app/controllers/dragons_controller.rb
- app/models/dragon.rb
- app/views/dragons/edit.html.erb
- app/views/dragons/index.html.erb
- app/views/dragons/new.html.erb
added validations and price to all forms
fixed text decorations on cards
added map in container
> added validations and price to all forms - fixed text dec on cards

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/views/dragons/index.html.erb
- db/schema.rb
> Added footer

- app/assets/stylesheets/components/_map.scss
- app/views/dragons/index.html.erb
- app/views/layouts/application.html.erb
> created frame for map

- app/assets/stylesheets/components/_map.scss
- app/views/dragons/index.html.erb
> changed footer

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_button.scss
- app/views/accounts/index.html.erb
- app/views/dragons/index.html.erb
- app/views/shared/_banner.html.erb
> aligned buttons on accounts page

- app/views/accounts/index.html.erb
> fixed the code

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_showpage-picture-boarder.scss
- app/views/dragons/show.html.erb
- app/views/shared/_review-form.html.erb
> fixed showpage
